extern crate formality;

pub mod document;
use document::*;

fn main() {
    // Prints an example Document in Rust
    let document : Document = vec![
        Element::Circle{x: 30, y: 30, r: 20},
        Element::Square{x: 60, y: 60, r: 20}
    ];
    println!("{:?}", document);

    // Printing a document generated by Formality code
    println!("{:?}", code_to_document(b"
        let pretty_circle
            Element.circle(uint(20), uint(20), uint(10))

        let pretty_square
            Element.square(uint(40), uint(40), uint(10))

        let main
            Document.cons(pretty_circle,
            Document.cons(pretty_square,
            Document.nil))
    ").unwrap());

}
